### ISSUE TITLE
Improve the theme name to CSS class transformation

### ISSUE THREAD

**Issue by Evelf** [lukemt/obsidian-theme-snippet-tailor#2]
The specifications for a valid CSS class are [here](https://developer.mozilla.org/en-US/docs/Web/CSS/ident), we should make sure our classes are valid.

**Comment by lukemt** [comment]
just improved on this one: https://github.com/lukemt/obsidian-theme-snippet-tailor/commit/09143867a6f6f63c8bb1ff86de86ff8bf268f30a
